language: android
android:
  components:
    - android-28

before_install:
  - curl -O https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v0.8.2-beta.tar.xz
  - tar xf flutter_linux_v0.8.2-beta.tar.xz
  - export PATH="$(pwd)/flutter/bin:$PATH"
  - flutter config --no-analytics
  - flutter doctor

script:
  - flutter build apk
  - flutter analyze .
  - flutter test
